# *Inspired by chatGpt*

stages:
  - build

build_arduino:
  stage: build
  script:
    - docker build -t wio_terminal_image ./wio_terminal
    - docker run --name wio_terminal_container wio_terminal_image
    - docker cp wio_terminal_container:wio_terminal/build/wio_terminal.ino.bin .
    - docker stop wio_terminal_container
    - docker rm wio_terminal_container
  tags:
    - shell
  artifacts:
    paths:
      - wio_terminal.ino.bin

build_android:
  stage: build
  script:
    - cd android
    - ./gradlew build
  tags:
    - android
