# *Inspired by chatGpt*

stages:
  - build

build_android:
  stage: build
  image: docker:latest # Docker container containing docker
  services:
    - docker:dind
  script:
    - docker build -t android ./android # Builds the docker android docker container
  artifacts:
    paths:
      - app/build/outputs/
